rust_library(
    name = "execution-engine",
    srcs = glob(["**/*.rs"]),
    crate_root = "lib.rs",
    visibility = ["//node/..."],
    deps = [
        "//third-party/rust:anyhow",
        "//third-party/rust:async-trait",
        "//third-party/rust:log",
        "//third-party/rust:serde",
        "//third-party/rust:tokio",
        "//common:common",
        "//cas:cas",
    ],
)
