rust_library(
    name = "services",
    srcs = glob(["*.rs"]),
    crate_root = "lib.rs",
    visibility = ["//node/..."],
    deps = [
        "//proto:protos",
        "//third-party/rust:log",
        "//third-party/rust:serde",
        "//third-party/rust:tokio",
        "//third-party/rust:tokio-stream",
        "//third-party/rust:tonic",
        "//common:common",
        "//cas:cas",
        "//execution:execution-engine",
    ],
)
