[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "fake"
path = "."

[dependencies]
tonic = "0.9"
tokio = { version = "1.0", features = ["fs", "macros", "rt-multi-thread", "io-util", "process" ] }
prost = "0.11"
prost-types = "0.11"
futures = "0.3"
openat2 = "0.1"
uuid = { version = "1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
tonic-build = "0.9"
toml = "0.7.3"
clap = { version = "4.2.5", features = [ "derive" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0.96"
pretty_env_logger = "0.4.0"
log = "0.4.17"
tokio-stream = {version = "0.1.14", features = [ "net" ] }
thiserror = "1.0.40"
regex = "1.8.1"
once_cell = "1.17.1"
async-trait = "0.1.68"
anyhow = "1.0.71"
tempdir = "0.3.7"
libc = "0.2.142"
sha2 = "0.10.6"
base16ct = { version = "0.2.0", features = ["std"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tracing-chrome = "0.7.1"
tempfile = "3.5.0"
tower = "0.4.13"
warp = "0.3.5"
yew = { version = "0.20", features = ["csr"] }
gloo = "0.8.0"
web-sys = "0.3.61"
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"
fuser = "0.12.0"
criterion = { version = "0.5.1", features = ["async_tokio"] }
