rust_library(
    name = "common",
    srcs = glob(["**/*.rs"]),
    crate_root = "lib.rs",
    visibility = ["PUBLIC"],
    doctests = False,
    deps = [
        "//proto:protos",
        "//third-party/rust:once_cell",
        "//third-party/rust:serde",
        "//third-party/rust:thiserror",
        "//third-party/rust:regex",
    ],
)
