rust_library(
    name = "cas",
    srcs = glob(["**/*.rs"]),
    crate_root = "lib.rs",
    visibility = ["//node/...", "//execution/..."],
    deps = [
        "//third-party/rust:async-trait",
        "//third-party/rust:base16ct",
        "//third-party/rust:log",
        "//third-party/rust:sha2",
        "//third-party/rust:thiserror",
        "//third-party/rust:tokio",
        "//common:common",
    ],
)
